# Generated by Django 4.2.5 on 2023-09-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_serviceuse_delete_secretekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceuse',
            name='last_hit',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
