# Generated by Django 4.2.5 on 2023-09-19 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='has_subscribed',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Basic'), (2, 'Pro')], default=1),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(2, 'Credit use'), (1, 'Credit gain'), (4, 'Payment'), (3, 'Credit expire')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
